# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
pod 'MJRefresh', '~> 3.0.8'

target 'TFLoadingPlaceHolder' do

end

target 'TFLoadingPlaceHolderTests' do

end

target 'TFLoadingPlaceHolderUITests' do

end

